name: workflow
on: 
  workflow_dispatch:
    inputs:
      version:
        desccription: "image version"
        deafault: 'v1.0.0'
jobs:
  preapare:
    runs-on: self-hosted
    steps:
      - name: docker login
        run: docker login -u supachai01 -p 'Supachai@0017'